### ISSUE TITLE
CPS2 - Super Street Fighter II X Grand Master Challenge (Japan 940223) - Reset when Selecting O. Dee Jay

### ISSUE THREAD

**Issue by springah** [jotego/jtcps#110]
When playing any of the SSF2 Grand Master Challenge MRAs (except Phoenix Edition) and selecting Original Dee Jay as a character (highlight Dee Jay, press Light Punch, then Down Down Up Up Heavy Punch), the game resets as the match is about to begin.

Apparently a known issue, but unable to find it reported here.

**Comment by Tuxosaurus** [comment]
I can confirm, also with version 940311 and the freeplay hacks.

Here it is on video: https://drive.google.com/file/d/1TtECqYrBSW9Gn90MnyltJ9dHLhaM-E5B/view?usp=sharing

To reproduce, select DeeJay and then input Down Down Up Up + Light Punch (you'll hear him say "alright!")

**Comment by springah** [comment]
Confirmed working in Phoenix Edition.

**Comment by jotego** [comment]
Still happens in eee00ef after improving jtframe_romrq

**Comment by jotego** [comment]
The decrypter address range was wrong. Fixed in bf5a34e
