### ISSUE TITLE
CPS 1 - Knigth of the Round - Missing raw pixel on the left side and maybe right side (or it is shifted to the left)

### ISSUE THREAD

**Issue by wwark** [jotego/jtcps#129]
You can see it on those both screenshot
(taking on 20211017)
![20210117_103321-screen](https://user-images.githubusercontent.com/469461/164913084-a7abdd1f-db60-42d6-a51a-58e1455480a1.png)
(last cores)
![20220112_232628-screen](https://user-images.githubusercontent.com/469461/164913102-75c0657d-de3b-43c1-bc9f-a9b37d59492d.png)

On the portrait of Lancelot, we see a missing blue part on the left side and visible on previous cores.

Thanks

**Comment by atrac17** [comment]
Tied to #132

**Comment by jotego** [comment]
Same as #132. Fixed in edd0cb9

**Comment by wwark** [comment]
Great thank you @jotego and @atrac17 
Will test it on the next release !
