### ISSUE TITLE
cps1 - 3 Wonders - intro glitch

### ISSUE THREAD

**Issue by barbudreadmon** [jotego/jtcps#131]
Seen on a friend's mister last week, i don't own one.

See pcb video at https://www.youtube.com/watch?v=UiJeLfruoh4&t=71s , the gun isn't supposed to be cut but it's cut on mister.

**Comment by atrac17** [comment]
Reference #132 

Last working build is [20211206](https://github.com/jotego/jtbin/blob/master/mister/cps1/releases/jtcps1_20211206.rbf) (JTCPS1 v9f4b585).

![20220619_104115-screen](https://user-images.githubusercontent.com/32810066/174477135-6e8f3874-5d82-44bd-a068-47175181eb8b.png)

Current build is [20220601](https://github.com/jotego/jtbin/blob/master/mister/cps1/releases/jtcps1_20220601.rbf) (JTCPS1 v40add73).

![20220619_104543-screen](https://user-images.githubusercontent.com/32810066/174477225-c6c02177-63b4-4eb8-88e1-b046ee63d72a.png)

**Comment by jotego** [comment]
Thanks @barbudreadmon for the PCB video.
Thanks @atrac17 for providing the history information. I've reverted the compromising change in edd0cb9. This fixes this issue but reopens #40.
