### ISSUE TITLE
Final Fight: check layer alignment

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps#132]
Check whether this is correct

![ffight](https://user-images.githubusercontent.com/1863036/172022692-77744533-17d1-4eef-a4b5-cd1d78dde9cf.png)

**Comment by atrac17** [comment]
The priority issues are present in other CPS1 titles. Final Fight is not the only title effected. I was able to trace this back to the last known working build.

Last working build is [20211206](https://github.com/jotego/jtbin/blob/master/mister/cps1/releases/jtcps1_20211206.rbf) (JTCPS1 v9f4b585).

![20220619_100010-screen](https://user-images.githubusercontent.com/32810066/174475706-570bc1b1-c43a-4096-859e-06dfe7a24f74.png)

![20220614_202848-screen](https://user-images.githubusercontent.com/32810066/174475933-f38b8ca1-c45e-4938-a4a3-53017d39d745.png)


Current build is [20220601](https://github.com/jotego/jtbin/blob/master/mister/cps1/releases/jtcps1_20220601.rbf) (JTCPS1 v40add73).

![20220619_100535-screen](https://user-images.githubusercontent.com/32810066/174475893-dd4f8626-fbbb-4b6e-8701-3fdb13f7e019.png)

![20220614_202848-screen](https://user-images.githubusercontent.com/32810066/174475937-18388abe-0ca8-4020-b454-b0df3c80e7d1.png)

Traced back to the following commits:

[4cef041](https://github.com/jotego/jtcps/commit/4cef041467b0fea679848870385c073a28a18d8f)
[0fdcb02](https://github.com/jotego/jtcps/commit/0fdcb021b95a30dc7bf548203660dcb2f20e56e7)

**Comment by jotego** [comment]
Thanks @atrac17 for providing the history information. I've reverted the compromising change in edd0cb9. This fixes this issue but reopens #40.
