### ISSUE TITLE
Night Warriors: raster effect?

### ISSUE THREAD

**Issue by jotego** [jotego/jtcps#133]
From Professor Jones in Discord

> I found another small graphical bug, in Night Warriors (World), using the latest CPS2 core (20220601) : in Pyron's stage, when descending from a jump, there's an horizontal line that forms for a brief time (seems like the layer is "separating"). I'm sorry for the bad quality of the pictures, I had to take screens from a video. Here's a link to the [video](https://photos.app.goo.gl/enZbxzoC8Ziv2izz6).

![unknown](https://user-images.githubusercontent.com/1863036/172046965-621e9e52-42ad-4944-bdd2-f09ee03a02e3.png)

**Comment by atrac17** [comment]
Please see [here](https://github.com/JTFPGA/jtalpha/issues/28). This was verified as being a function on real hardware back in July of 2021. Reference [video](https://www.youtube.com/watch?v=dqUuGBbKHaU) is here.

**Comment by jotego** [comment]
Thanks for the references. I'll close the issue.
