### ISSUE TITLE
wrong sound in king of dragon and captain commando

### ISSUE THREAD

**Issue by titorin0** [jotego/jtcps#141]
In the first stage of captain commando the cymbals are perceived very strident.
they are not corrected by touching the filters.

the same goes for the king of dragon in stage 4 .
becoming unpleasant
https://youtube.com/clip/UgkxhsKSqb7QJffJFQkWv4YaObqXCOb_Gsxo
real pcb kod: https://youtube.com/clip/Ugkx30RhvkV-J4ZiMGVQeUj8xLZeA2Rg3CZ3

https://youtube.com/clip/UgkxO7wt1Am9h_BWJhiZ_K9NUSGeHzs6rsx1
real captain pcb: https://youtube.com/clip/Ugkx5FEH_Dr24ocC1RRvmCN5CZdFSEakpOx9

**Comment by TesterNes** [comment]
That Captain Commando's video is not from a real pcb but MAME32Plus!Plus!0.116u3
This is from a real one: https://www.youtube.com/watch?v=0o9Utr5rjFQ
Anyway, this is related to https://github.com/jotego/jtcps/issues/145

**Comment by jotego** [comment]
Close as duplicated. We will track it in #145
