### ISSUE TITLE
Puzzloop2/CPS2 Spinner support

### ISSUE THREAD

**Issue by eedomus** [jotego/jtcps#144]
By Default, Puzzloop is configured to be played with a joystick.

But you can enable spinner control going to "Test Menu / Configuration / Operation"

Playing this game with a spinner is a nice added value on the gameplay 🥰

![image](https://user-images.githubusercontent.com/35696861/200190036-10f6b044-d870-48d8-a9ec-5b0d476a57e8.png)

![image](https://user-images.githubusercontent.com/35696861/200190095-f3b4ef66-83ba-49a5-9ec9-d513b258f804.png)

**Comment by jotego** [comment]
The spinner logic is currently not connected to the CPU. Apparently, there are two games using the spinner and the hardware is slightly different.

To do:

- [ ] connect spinner to JTCPS2
- [ ] Eco Fighters mode
- [ ] Puzz Loop 2 mode

**Comment by capitaineflam25** [comment]
Thanks for the explanation 👍🏻

**Comment by jotego** [comment]
Completed on e1c67c9
To be released this Friday
