### ISSUE TITLE
Speed increase with SF2 Hyper Fighting

### ISSUE THREAD

**Issue by sqwirral** [jotego/jtcps#146]
The speed of SF2HF seems to have been changing between releases.

It was pretty good back in 20210131. Here's a video by fluxcore comparing 20210131 to real hardware:
https://www.youtube.com/watch?v=2nJiMnxXYVA

Here is a video (posted by Ohmi) comparing the current 20220819 to a real HF board, and the core runs too fast:
https://drive.google.com/file/d/1FNYcXS0yum-oKHpksb2RO4Xx8hH1cAg5/view?usp=share_link

I tested a lot of RBF's (using Street Fighter II'  Hyper Fighting -World 921209-.mra) and found the speed has changed a lot in both directions between versions. Here's a video with 15 synced together:
https://www.youtube.com/watch?v=kW-OaRdK7IU

It may be easier to visualise the changes when looking at the end times of the above video:
![image](https://user-images.githubusercontent.com/243372/203403328-ae78040f-8646-400c-9050-233b9dae1d19.png)

(Note, I also tested the same versions a second time, to make sure it wasn't giving totally different results each run. While not frame-exact, they were very close when sticking to the same version, so I don't think that's a problem.)

**Comment by jotego** [comment]
Some changes in how the /DTACK signal is handled have affected the core performance over time. This is a collection of the different values recorded using _SF2 DMA no b3.mra_ These tests measure the CPU speed under different DMA settings. In this table I am just comparing the default value. Note that the numbers are in hexadecimal.

Version         | commit  | Speed     | JTFRAME
----------------|---------|-----------|-------------------------
Original PCB    |  N/A    |  2C00     |
20210131        |         |  2C04     |
20210604        |         |  2C0A     |
20210828        |         |  2C0B     |
20210921        |         |**357C**   |
20211002        |         |  357C     |
20211024        |         |  357C     |
20220112        |         |  3584     |
20220321        |         |  3584     |
20220417        |         |**2BF9**   |
20220422        |         |  2BF9     |
20220427        |         |  2BF9     |
20220601        |         |  2BF9     |
20220627        |         |  2BF9     |
20220704        |         |  2BF9     |
20220705        | 61626fc |  2BF9     |  bd7cf34
20220819        | b78bdae |**3576**   |  a108a4a

The immediate action is to [delete version 20220819](https://github.com/jotego/jtbin/commit/7059c052a419959bf5c3fdd335b4b7bfc7c10126). I keep the issue open until the source code incorporates the fix.

**Comment by jotego** [comment]
- The changes in the jtframe_68kdtack module in [JTFRAME](https://github.com/jotego/jtframe/commit/fa2d6a1a78d3d41b57ae12030c54f8096d01d8b0)  caused the speed increase
- Fixed in bd63249
