### ISSUE TITLE
Add a Flip Screen option for analog output (CRT) on some vertical games (19xx)

### ISSUE THREAD

**Issue by capitaineflam25** [jotego/jtcps#148]
Thanks for this great core.

Sometime your vertical CRT is not orientated the right way and can't be physically rotated, a "Flip Screen" option would be a nice enhancement.

19xx has a japanese service menu, maybe there is a hidden flip screen option in it ?

**Comment by atrac17** [comment]
It's in the service menu, any region. There are no dips for CPS2 dips. It's all in the eeprom/nvram.

**Comment by capitaineflam25** [comment]
Thanks for your help. Do you know which menu item it is in 19xx ? It's all japanese 🇯🇵

**Comment by jotego** [comment]
The required option is shown with the asterisk. If you need more help use your mobile phone screen translator or use the English version of the game.

![20221211_093116-screen](https://user-images.githubusercontent.com/1863036/206894054-806d16e3-0445-4a42-8f9a-f06c3bfb4622.png)
![20221211_093219-screen](https://user-images.githubusercontent.com/1863036/206894055-ab7b11ea-9e8e-45ea-91d5-50cd018ebf4e.png)
![20221211_093213-screen](https://user-images.githubusercontent.com/1863036/206894058-a4981c14-1d0d-4aa8-a994-3ba784230c07.png)

**Comment by capitaineflam25** [comment]
Thanks a lot for those tips !
