### ISSUE TITLE
Add ability to change sensativity and rotation speed of Forgotten Worlds analog rotation like in mame

### ISSUE THREAD

**Issue by konradpop** [jotego/jtcps#155]
due to various rotary joystick interfaces the response on the rotation can be slow with this game, mame has a feature for analog rotary sensitivity and speed so that the character can spin faster or slower etc. Is this possible in this, Using DaemonBite joystick with rotary interface + LS30 joysticks, the default rotation speed is too slow in the game.

**Comment by jotego** [comment]
Completed in 968dfba
- Added OSD option with 4 speeds for rotation
- Rotation is mapped to two joystick buttons
- Rotation can be controlled with a spinner
I will update the version in JTBIN on Friday
