### ISSUE TITLE
Adding high score saving

### ISSUE THREAD

**Issue by theenemy-thd** [jotego/jtcps#159]
Are there any plans to add high score saving at all, It would obviously be great on all your cores to have highs saved.

**Comment by jotego** [comment]
Yes, a lot of ground work has already been done in the last two months to pave the road to hi-score saving. 
If you check the repository logs, the modifications done to add a file called mem.yaml to many cores is related to this. 
I cannot commit to a specific date for this change but it's coming.
Let me close this issue as I think this task was already captured in a different one.
